/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

game.resources = {
    /* Graphics. */
    "img" : [
        // UI
        "dialog",
        "heart_empty",
        "heart_half",
        "heart_full",

        // Characters
        "player",
        "player_eyes",
        "abi",
        "abi_eyes",
        "george",
        "george_eyes",
        "james",
        "james_eyes",
        "jessica",
        "jessica_eyes",
        "whitey",
        "whitey_eyes",
        "char_shadow",
        "snake",

        // Collectibles
        "coin_gold",
        "coin_silver",
        "coin_shadow",
        "hammer",

        // Interactive objects
        "chests",
        "silver_keys",

        // Tilesets
        "accessories",
        "animwater",
        "barrel",
        "bridges",
        "buckets",
        "cabinets",
        "castlefloors_outside",
        "country",
        "castlewalls",
        "castle_outside",
        "castlefloors",
        "dark_library_stuff",
        "dirt",
        "dirt2",
        "doors",
        "dungeon",
        "farming_fishing",
        "fence",
        "fence_alt",
        "floor",
        "flowers_2",
        "grass",
        "grassalt_flowers",
        "house",
        "housey",
        "inside",
        "kitchen",
        "misc",
        "mountains",
        "sandwater",
        "shadow",
        "signs",
        "snow",
        "snowcoldwater",
        "snowice",
        "snowwater",
        "snowwateralt",
        "stairs",
        "stonepattern",
        "tile_a1",
        "tile_a2",
        "tile_a3",
        "tile_a4",
        "tile_a5",
        "tile_b",
        "tile_c",
        "tile_d",
        "tile_e",
        "town_buildings",
        "tree_stump",
        "treetop",
        "trunk",
        "victoria",
        "victorian_house",
        "windmill"
    ],

    /* Maps from Tiled. */
    "map" : [
        "players_room",
        "players_house",
        "world",
        "empty_room",
        "library",
        "winterfell",
        "dungeon",
        "castle",
        "castle_interior"
    ],

    /* 1-channel audio. Usually sound effects. */
    "sfx" : [
        "chests",
        "collect_coin",
        "dying",
        "fanfare",
        "hurt",
        "mallet_swing",
        "mallet_whomp"
    ],

    /* 2-channel audio. Usually music. */
    "bgm" : [
        "bells",
        "del_erad",
        "pink_and_lively",
        "random_and_cheap",
        "nyan_cat_original"
    ]
};

game.info = {
    "audio_error" : [
        {
            "messages" : [
                "Your browser does not support Ogg-Vorbis audio.",
                "Sounds have been disabled.",
                "",
                "Press [Enter] or [Space] to continue."
            ]
        }
    ]
};

game.story = {
    // max about 76 chars per line
    "intro" : [
        {
            "image" : null,
            "messages" : [
                "A long time ago (1949), in a land far, far away (Japan) ...",
                "A guy called Tadashi-kun decided to open a clothing shop."
            ]
        },
        {
            "image" : null,
            "messages" : [
                "The company was called Ogori Shoji and they only sell men clothes.",
                "In 1985, the company decided to expand their business and starts selling",
                "unisex casual wear. This new company is called UNIQLO (Unique Clothing)",
                "while the original company is renamed to Fast Retailing in 1991."
            ]
        },
        {
            "images": null,
            "messages": [
                "This is the story of Tadashi-kun and his journey to WORLD DOMINATION ..."
            ]
        }
    ],

    "gameover" : [
        {
            "image" : null,
            "messages" : [
                "Fool! you died.",
                "This isn't your time yet ...",
                "",
                "You're going back now,",
                "and that was all like just a dream ...",
                "Good luck!",
                "",
                "Press [Enter] or [Space] to continue."
            ]
        }
    ]
};

game.credits = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Concept :",
    "                                   ... Jason Oster",
    "    http://www.kodewerx.org/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Programming :",
    "",
    "",
    "  Neverwell Moor",
    "                                   ... Jason Oster",
    "    http://www.kodewerx.org/",
    "    *The MIT License",
    "    *GNU GPL 3.0 or later",
    "",
    "  melonJS-0.9.4.js",
    "  melonJS                          ... Olivier Biot, et al.",
    "    http://www.melonjs.org/",
    "    *The MIT License",
    "",
    "  cp.js",
    "  Chipmunk-js                      ... Scott Lembcke, Joseph Gentle, et al.",
    "    https://github.com/josephg/Chipmunk-js/",
    "    *The MIT License",
    "",
    "  minpubsub.js",
    "  MinPubSub                        ... Daniel Lamb",
    "    https://github.com/daniellmb/MinPubSub/",
    "    *The MIT License",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Original Art Work :",
    "",
    "",
    "  flowers_2.png",
    "  housey.png",
    "  town_buildings.png",
    "                                   ... Guido Bos",
    "    http://opengameart.org/content/lpc-guido-bos-entries-cut-up",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  dialog.png",
    "                                   ... Thane Brimhall (AKA Pennomi)",
    "    http://opengameart.org/content/lpc-pennomis-ui-elements",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  doors.png",
    "                                   ... Pol Camara (AKA PolCPP)",
    "    http://opengameart.org/comment/reply/10851/11360",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  abi.png",
    "  abi_eyes.png",
    "  george.png",
    "  george_eyes.png",
    "  jessica.png",
    "  jessica_eyes.png",
    "  rachel.png",
    "  rachel_eyes.png",
    "  whitey.png",
    "  whitey_eyes.png",
    "                                   ... Radomir Dopieralski (AKA Sheep)",
    "    http://opengameart.org/lpc-art-entries",
    "    http://opengameart.org/content/one-more-lpc-alternate-character",
    "    http://opengameart.org/content/alternate-lpc-character-sprites-george",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  sandwater.png",
    "  farming_fishing.png",
    "  fence.png",
    "  fence_alt.png",
    "                                   ... Daniel Eddeland",
    "    http://opengameart.org/content/lpc-farming-tilesets-magic-animations-",
    "    and-ui-elements",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  grassalt_flowers.png",
    "  stonepattern.png",
    "  victorian_house.png",
    "  windmill.png",
    "                                   ... Casper Nilsson",
    "    http://opengameart.org/lpc-art-entries",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  snake.png",
    "                                   ... Charles Sanchez (AKA CharlesGabriel)",
    "    http://lpc.opengameart.org/static/lpc-style-guide/authors.html",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  barrel.png",
    "  buckets.png",
    "  bridges.png",
    "  cabinets.png",
    "  chests.png",
    "  country.png",
    "  dirt2.png",
    "  dirt.png",
    "  grass.png",
    "  house.png",
    "  inside.png",
    "  kitchen.png",
    "  mountains.png",
    "  shadow.png",
    "  signs.png",
    "  stairs.png",
    "  treetop.png",
    "  trunk.png",
    "  victoria.png",
    "  watergrass.png",
    "                                   ... Lanea Zimmerman (AKA Sharm)",
    "    http://lpc.opengameart.org/static/lpc-style-guide/authors.html",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0 or later",
    "",
    "",
    "  accessories.png",
    "                                   ... Thane Brimhall (AKA Pennomi)",
    "    http://opengameart.org/content/lpc-tabletop-rpg-pizza",
    "                                   ... Jetrel",
    "    http://opengameart.org/content/rpg-item-set",
    "    *CC0",
    "",
    "",
    "  heart_empty.png",
    "  heart_full.png",
    "  heart_half.png",
    "                                   ... Casper Nilsson",
    "    http://opengameart.org/content/simple-small-pixel-hearts",
    "    *CC-BY-SA 3.0",
    "",
    "",
    "  floor.png",
    "                                   ... Stephen Challener (AKA Redshrike)",
    "    http://opengameart.org/content/16x16-indoor-rpg-tileset-the-baseline",
    "    *CC-BY-SA 3.0",
    "",
    "",
    "  misc.png",
    "                                   ... Matthew Nash",
    "    http://opengameart.org/content/misc-32x32-tiles",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0",
    "    *GNU GPL 2.0",
    "",
    "",
    "  coin_gold.png",
    "  coin_silver.png",
    "  coin_shadow.png",
    "                                   ... Chris Bellanger",
    "    http://opengameart.org/content/animated-coins",
    "    *CC-BY 3.0",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0",
    "    *GNU GPL 2.0",
    "",
    "",
    "  char_shadow.png",
    "  logo.png",
    "  hammer.png",
    "                                   ... Jason Oster",
    "    *CC0",
    "",
    "",
    "  Small modifications",
    "                                   ... Jason Oster",
    "    *CC0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Music :",
    "",
    "",
    "  bells.ogg",
    "                                   ... Nelson James Gatlin",
    "    http://opengameart.org/lpc-art-entries",
    "    *CC-BY-SA 3.0",
    "    *GNU GPL 3.0",
    "",
    "",
    "  del_erad.ogg",
    "                                   ... Janne Hanhisuanto for Radakan",
    "    http://opengameart.org/content/radakan-del-erad",
    "    *CC-BY-SA 3.0",
    "",
    "",
    "  pink_and_lively.ogg",
    "  random_and_cheap.ogg",
    "                                   ... atrk-bu (Auto-generated)",
    "    https://github.com/iamgreaser/it2everything/blob/master/atrk-bu.py",
    "    *CC-0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sound Effects :",
    "",
    "",
    "  fanfare.ogg",
    "                                   ... jivatma07",
    "    http://www.freesound.org/people/jivatma07/sounds/122255/",
    "    *CC-BY-SA 3.0",
    "",
    "",
    "  mallet_swing.ogg",
    "  mallet_whomp.ogg",
    "                                   ... Etherian",
    "    http://opengameart.org/comment/reply/11373/12927",
    "",
    "",
    "  chests.ogg",
    "  collect_coin.ogg",
    "  dying.ogg",
    "  hurt.ogg",
    "                                   ... cfxr (Auto-generated)",
    "    http://thirdcog.eu/apps/cfxr/",
    "    *CC-0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Level Design :",
    "                                   ... Jason Oster",
    "                                   ... Etherian",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "A Liberated Pixel Cup Production",
    "2012 Jason Oster",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                             For my Favorite",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
];
